# Lab 8
### Seg 3 - Kmeans - Hough

threshold_otsu: http://scikit-image.org/docs/dev/api/skimage.filters.html
                Good Visualization here: https://en.wikipedia.org/wiki/Otsu%27s_method
                
                

In [5]:
from commonfunctions import *

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
'''
Example
Array Indexing important note
'''
x= np.arange(10,0,-1)
indexesArray = np.array([3, 3, 1, 8])
print(x)
print(indexesArray)
print(x[indexesArray])
# Try it if x 

[10  9  8  7  6  5  4  3  2  1]
[3 3 1 8]
[7 7 9 2]


In [37]:
'''
@TODO
Requirement
Try the same concept on multidimensional array x
Don't forget to convert x to numpy array
'''
x=np.array([np.arange(10,0,-1),np.arange(0,10,1)])
indexArray=np.array([3,3,1,8])
print(x)
#print(indexArray)
print(x[0][indexArray])


[[10  9  8  7  6  5  4  3  2  1]
 [ 0  1  2  3  4  5  6  7  8  9]]
[7 7 9 2]


In [ ]:
image = io.imread('balls.jpg')
imgCopy=np.copy(image)
[x, y, z ]= image.shape
img2d = image.reshape(x*y, z)

## TODO: Construct kmeans object using cluster.KMeans with appropriate n_clusters
kmean=cluster.KMeans(50)
kmo=kmean.fit(img2d)
centers=kmo.cluster_centers_
labels=kmo.labels_

img2d=centers[labels]/255.0

img2d=img2d.reshape(x,y,z)
show_images([imgCopy,img2d],["original","segmented"])


## TODO: Fit the kmeans object with the data of the image

'''

TODO : use the attributes 
        ".cluster_centers_" to get the center of the RGB color to use per segment 
                             [I.e: contains the colors of the new segments]
        ".labels_": to get the label for each pixel of the input.
 Hint: print the shape of the output to understand it clearly.
'''

'''

TODO: For each label replace it with the corresponding RGB color according to the cluster_centers, cluster_labels
Hint: Use the same concept shown above

Reshape the image to be on the original shape
Show the original and the segmented image


'''


In [ ]:
'''

@TODO:
This experiment should be done on Gray scale and on one channel of RGB or HSV

use threshold_otsu to get the threshold that should be used to divide the values.
'''



In [ ]:
import numpy as np


def drawLine(ax,angle, dist):
    '''
    This function should draw the lines, given axis(ax), the angle and the distance parameters
    
    TODO:
    Get x1,y1,x2,y2
    '''
    
    
    
    # This line draws the line in red
    
    ax[1].plot((x1, y1), (x2, y2), '-r')

'''TODO: 
1- Read image
2- Get edges using Canny.
3- Show image and edges side-by-side.
4- Call hough lines on edges and get the results (houghSpace,angles, distances)
5- Get Hough Line Peaks with different thresholds: the default threshold is 0.5 *max(hspace)
* What is the effect of the threshold?
* What is the meaning of the outputs of hough_line,hough_line_peak? Hint:print them.
* Why do we use canny before hough?!
'''






## This part draw the lines on the image.

fig, axes = plt.subplots(1, 2, figsize=(20, 6))
ax = axes.ravel()

ax[0].imshow(image, cmap=cm.gray)
ax[0].set_title('Input image')
ax[0].set_axis_off()


ax[1].imshow(image, cmap=cm.gray)
for angle, dist in zip(angles,dists):
    drawLine(ax,angle, dist)
ax[1].set_xlim((0, image.shape[1]))
ax[1].set_ylim((image.shape[0], 0))
ax[1].set_axis_off()
ax[1].set_title('Detected lines')

plt.tight_layout()
plt.show()

